name: print secret
on: workflow_dispatch
jobs:
  debug:
    name: print-scret
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up secret file
      env:
        AWS_REGION: ${{ secrets.AWS_REGION }}
      run: |
        echo ${{secrets.AWS_REGION}} | sed 's/./& /g'
